name: Release
on:
  workflow_call:

env:
  GITHUB_OWNER: mysteriumnetwork
  GITHUB_REPO: node
  GITHUB_SNAPSHOT_REPO: node-builds
  GITHUB_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_METADATA_DISABLED: true
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    env:
      NIGHTLY_BUILD: true

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/download-artifact@v4
        with:
          name: env.sh
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release nightly snapshot
        run: |
          source env.sh
          go run mage.go -v ReleaseGithubNightly

      - name: Notify UptimeRobot
        run: curl -so /dev/null -I "${{ secrets.NIGHTLY_UPTIMEROBOT }}"

  release-snapshot:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' &&
      github.event_name != 'schedule'

    strategy:
      max-parallel: 3
      matrix:
        platform:
          - ReleaseGithubSnapshot
          - ReleaseDockerSnapshot
          - ReleaseDebianPPASnapshot

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/download-artifact@v4
        with:
          name: env.sh
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install devscripts build-essential lintian dput dh-make python3-paramiko
          echo -e "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa

      - name: Release snapshot
        run: |
          source env.sh
          go run mage.go -v ${{ matrix.platform }}

      - name: Release Go report
        if: github.ref == 'refs/heads/master'
        run: bin/release_goreport

  release-tag:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    strategy:
      max-parallel: 4
      matrix:
        platform:
          - ReleaseGithubTag
          - ReleaseDockerTag
          - ReleaseDebianPPAPreRelease
          # - ReleaseAndroidSDK
          # - ReleaseAndroidProviderSDK

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/download-artifact@v4
        with:
          name: env.sh
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install devscripts build-essential lintian dput dh-make python3-paramiko
          echo -e "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa

      - name: Release tag
        run: |
          source env.sh
          go run mage.go -v ${{ matrix.platform }}

  post-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [release-tag]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/download-artifact@v4
        with:
          name: env.sh
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR Avado
        run: |
          source env.sh
          go run mage.go -v CreateAvadoPR
